### ISSUE TITLE
Enable simple user-driven boolean validation in narrative schema

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#8]
It would be helpful to be able to define a label in a narrative schema that inserts a checkbox in the formatted document, and a rule that requires the checkbox to be ticked for the litvis to 'pass' linting.

Issue #7 would allow this to be achieved by providing an appropriate regex, but given this might be quite a common task, perhaps it would be better to define it as simple label / rule attributes and for litvis to insert the relevant markdown and rule validation logic.

For example, something like this (see `includeCheck`, `checkMustPass`):

```yaml
labels:
  - name: invariance
    includeCheck: true
    paired:
      htmlTemplate: 'Confirm that non-meaningful changes in data representation, such as table row order have no discernible effect on visualization.{{children}}</div>'

rules:
  - description: Kindlmann and Scheidegger's principle of data representation invariance.
    selector:
      label: invariance
    checkMustPass: true
```

There is an open question as to whether such a check should be attached to the 'question' or 'response' label (e.g. `invariance` or `invarianceAssessment` in [albebra.yaml](https://github.com/gicentre/litvis/blob/master/narrative-schemas/algebra.yml)) and whether an explicit message is required to be given if the box is not checked (currently this would be the `description` field in the rule).
